"""init schema

Revision ID: f85777ef854a
Revises: 211203defb0c
Create Date: 2025-10-07 01:27:03.156712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85777ef854a'
down_revision: Union[str, Sequence[str], None] = '211203defb0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # skills
    op.create_table(
        "skills",
        sa.Column("skill_id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name_canonical", sa.Text(), nullable=False, unique=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("aliases_json", sa.Text(), nullable=False, server_default="[]"),
    )
    #jobs
    op.create_table('jobs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('company', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), server_default='N/A', nullable=True),
    sa.Column('region', sa.Text(), server_default='N/A', nullable=True),
    sa.Column('country', sa.Text(), server_default='N/A', nullable=True),
    sa.Column('remote_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('salary_min', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('salary_max', sa.Numeric(), server_default='0', nullable=False),
    sa.Column('salary_currency', sa.Text(), server_default='USD', nullable=False),
    sa.Column('salary_period', sa.Text(), server_default='yearly', nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Text(), server_default='manual', nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('description_text', sa.Text(), server_default='', nullable=False),
    sa.Column('url_hash', sa.LargeBinary(), nullable=True),
    sa.Column('desc_hash', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('url_hash', name='jobs_url_hash_uq')
    )
    op.create_index('jobs_desc_hash_idx', 'jobs', ['desc_hash'], unique=False)
    op.create_table('skills',
    sa.Column('skill_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_canonical', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('aliases_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('skill_id'),
    sa.UniqueConstraint('name_canonical')
    )
    op.create_table('job_skills',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_skills')
    op.drop_table('skills')
    op.drop_index('jobs_desc_hash_idx', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
