name: Nightly Ingest

on:
  schedule:
    - cron: "15 3 * * *"   # 03:15 UTC daily
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt || true
      - run: python -m ingest.nightly
        env:
          REQUEST_DELAY: "0.25"
          SOURCES_JSON: "data/sources.json"
          # Add secrets here if your pipeline writes to a remote DB:
          # DATABASE_URL: ${{ secrets.DATABASE_URL }}
